version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  redis:
    image: redis
    expose:
      - 6379
  web:
    build: .
    command: npm run build
    command: npm run db:migrate
    command: pm2-runtime start pm2.json
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
