version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10.16
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: node_base_test
          POSTGRES_PASSWORD: node_base_test
          POSTGRES_DB: node_base_test
    environment:
      NODE_ENV: test
      POSTGRES_USER: node_base_test
      POSTGRES_PASSWORD: node_base_test
      POSTGRES_DB: node_base_test
      DB_USER: node_base_test
      DB_PASSWORD: node_base_test
      DB_NAME: node_base_test
      DB_HOST: 127.0.0.1
    steps:
      - run:
          name: Install ltree extension for Postgres
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
            dockerize -wait tcp://localhost:5432 -timeout 1m
            psql -U node_base_test -h localhost -p 5432 -c 'create extension ltree'
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm run test
